### ISSUE TITLE
Can't build land trade route on Oasis

### ISSUE THREAD

**Issue by Semigradsky** [ravignir/RekMOD#189]
In Civilopedia I see that it is possible

![Screenshot_2024-04-18-00-06-21-731_com unciv app](https://github.com/ravignir/RekMOD/assets/1198848/f0d25ec1-2b62-4d71-bf83-21965268165a)

but option not avaible

![Screenshot_2024-04-18-00-06-38-617_com unciv app](https://github.com/ravignir/RekMOD/assets/1198848/89224fd4-16b1-49e3-98e6-c67c98725f62)

**Comment by SeventhM** [comment]
Huh... Never thought of that getting in the way

Should be fixed as of #191

**Comment by Semigradsky** [comment]
Still can't build on Oasis. But I don't know what version of RekMOD I have.

![Screenshot_2024-05-03-22-20-40-582_com unciv app](https://github.com/ravignir/RekMOD/assets/1198848/6ce165f0-c7f8-47b9-8e05-98e8b8bc9201)

![Screenshot_2024-05-03-22-21-10-847_com unciv app](https://github.com/ravignir/RekMOD/assets/1198848/37fae256-2a92-4d39-8dce-812df583a751)

**Comment by Stipidess** [comment]
No, I don't think the version matters.... I got RekMod on September 3, still cannot build on oasis.
